/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as ApiAsaasWebhookRouteImport } from './routes/api/asaas/webhook'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutAlertasRouteImport } from './routes/dashboard/_layout/alertas'
import { Route as DashboardLayoutAssinaturaRouteImport } from './routes/dashboard/_layout/assinatura'
import { Route as DashboardLayoutClimaRouteImport } from './routes/dashboard/_layout/clima'
import { Route as DashboardLayoutEquipeRouteImport } from './routes/dashboard/_layout/equipe'
import { Route as DashboardLayoutFuncionariosRouteImport } from './routes/dashboard/_layout/funcionarios'
import { Route as DashboardLayoutLeadsRouteImport } from './routes/dashboard/_layout/leads'
import { Route as DashboardLayoutLembretesRouteImport } from './routes/dashboard/_layout/lembretes'
import { Route as DashboardLayoutMarcaRouteImport } from './routes/dashboard/_layout/marca'
import { Route as DashboardLayoutPrecosRouteImport } from './routes/dashboard/_layout/precos'
import { Route as DashboardLayoutProdutoresRouteImport } from './routes/dashboard/_layout/produtores'
import { Route as DashboardLayoutRelatoriosRouteImport } from './routes/dashboard/_layout/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAsaasWebhookRoute = ApiAsaasWebhookRouteImport.update({
  id: '/api/asaas/webhook',
  path: '/api/asaas/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutAlertasRoute = DashboardLayoutAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutAssinaturaRoute =
  DashboardLayoutAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutClimaRoute = DashboardLayoutClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutEquipeRoute = DashboardLayoutEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutFuncionariosRoute =
  DashboardLayoutFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutLeadsRoute = DashboardLayoutLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutLembretesRoute =
  DashboardLayoutLembretesRouteImport.update({
    id: '/lembretes',
    path: '/lembretes',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutMarcaRoute = DashboardLayoutMarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutPrecosRoute = DashboardLayoutPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutProdutoresRoute =
  DashboardLayoutProdutoresRouteImport.update({
    id: '/produtores',
    path: '/produtores',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutRelatoriosRoute =
  DashboardLayoutRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/api/asaas/webhook': typeof ApiAsaasWebhookRoute
  '/dashboard/alertas': typeof DashboardLayoutAlertasRoute
  '/dashboard/assinatura': typeof DashboardLayoutAssinaturaRoute
  '/dashboard/clima': typeof DashboardLayoutClimaRoute
  '/dashboard/equipe': typeof DashboardLayoutEquipeRoute
  '/dashboard/funcionarios': typeof DashboardLayoutFuncionariosRoute
  '/dashboard/leads': typeof DashboardLayoutLeadsRoute
  '/dashboard/lembretes': typeof DashboardLayoutLembretesRoute
  '/dashboard/marca': typeof DashboardLayoutMarcaRoute
  '/dashboard/precos': typeof DashboardLayoutPrecosRoute
  '/dashboard/produtores': typeof DashboardLayoutProdutoresRoute
  '/dashboard/relatorios': typeof DashboardLayoutRelatoriosRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/api/asaas/webhook': typeof ApiAsaasWebhookRoute
  '/dashboard/alertas': typeof DashboardLayoutAlertasRoute
  '/dashboard/assinatura': typeof DashboardLayoutAssinaturaRoute
  '/dashboard/clima': typeof DashboardLayoutClimaRoute
  '/dashboard/equipe': typeof DashboardLayoutEquipeRoute
  '/dashboard/funcionarios': typeof DashboardLayoutFuncionariosRoute
  '/dashboard/leads': typeof DashboardLayoutLeadsRoute
  '/dashboard/lembretes': typeof DashboardLayoutLembretesRoute
  '/dashboard/marca': typeof DashboardLayoutMarcaRoute
  '/dashboard/precos': typeof DashboardLayoutPrecosRoute
  '/dashboard/produtores': typeof DashboardLayoutProdutoresRoute
  '/dashboard/relatorios': typeof DashboardLayoutRelatoriosRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/api/asaas/webhook': typeof ApiAsaasWebhookRoute
  '/dashboard/_layout/alertas': typeof DashboardLayoutAlertasRoute
  '/dashboard/_layout/assinatura': typeof DashboardLayoutAssinaturaRoute
  '/dashboard/_layout/clima': typeof DashboardLayoutClimaRoute
  '/dashboard/_layout/equipe': typeof DashboardLayoutEquipeRoute
  '/dashboard/_layout/funcionarios': typeof DashboardLayoutFuncionariosRoute
  '/dashboard/_layout/leads': typeof DashboardLayoutLeadsRoute
  '/dashboard/_layout/lembretes': typeof DashboardLayoutLembretesRoute
  '/dashboard/_layout/marca': typeof DashboardLayoutMarcaRoute
  '/dashboard/_layout/precos': typeof DashboardLayoutPrecosRoute
  '/dashboard/_layout/produtores': typeof DashboardLayoutProdutoresRoute
  '/dashboard/_layout/relatorios': typeof DashboardLayoutRelatoriosRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinar'
    | '/login'
    | '/onboarding'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/dashboard'
    | '/api/asaas/webhook'
    | '/dashboard/alertas'
    | '/dashboard/assinatura'
    | '/dashboard/clima'
    | '/dashboard/equipe'
    | '/dashboard/funcionarios'
    | '/dashboard/leads'
    | '/dashboard/lembretes'
    | '/dashboard/marca'
    | '/dashboard/precos'
    | '/dashboard/produtores'
    | '/dashboard/relatorios'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar'
    | '/login'
    | '/onboarding'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/api/asaas/webhook'
    | '/dashboard/alertas'
    | '/dashboard/assinatura'
    | '/dashboard/clima'
    | '/dashboard/equipe'
    | '/dashboard/funcionarios'
    | '/dashboard/leads'
    | '/dashboard/lembretes'
    | '/dashboard/marca'
    | '/dashboard/precos'
    | '/dashboard/produtores'
    | '/dashboard/relatorios'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/assinar'
    | '/login'
    | '/onboarding'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/dashboard/_layout'
    | '/api/asaas/webhook'
    | '/dashboard/_layout/alertas'
    | '/dashboard/_layout/assinatura'
    | '/dashboard/_layout/clima'
    | '/dashboard/_layout/equipe'
    | '/dashboard/_layout/funcionarios'
    | '/dashboard/_layout/leads'
    | '/dashboard/_layout/lembretes'
    | '/dashboard/_layout/marca'
    | '/dashboard/_layout/precos'
    | '/dashboard/_layout/produtores'
    | '/dashboard/_layout/relatorios'
    | '/dashboard/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinarRoute: typeof AssinarRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  ApiAsaasWebhookRoute: typeof ApiAsaasWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asaas/webhook': {
      id: '/api/asaas/webhook'
      path: '/api/asaas/webhook'
      fullPath: '/api/asaas/webhook'
      preLoaderRoute: typeof ApiAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/alertas': {
      id: '/dashboard/_layout/alertas'
      path: '/alertas'
      fullPath: '/dashboard/alertas'
      preLoaderRoute: typeof DashboardLayoutAlertasRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/assinatura': {
      id: '/dashboard/_layout/assinatura'
      path: '/assinatura'
      fullPath: '/dashboard/assinatura'
      preLoaderRoute: typeof DashboardLayoutAssinaturaRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/clima': {
      id: '/dashboard/_layout/clima'
      path: '/clima'
      fullPath: '/dashboard/clima'
      preLoaderRoute: typeof DashboardLayoutClimaRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/equipe': {
      id: '/dashboard/_layout/equipe'
      path: '/equipe'
      fullPath: '/dashboard/equipe'
      preLoaderRoute: typeof DashboardLayoutEquipeRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/funcionarios': {
      id: '/dashboard/_layout/funcionarios'
      path: '/funcionarios'
      fullPath: '/dashboard/funcionarios'
      preLoaderRoute: typeof DashboardLayoutFuncionariosRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/leads': {
      id: '/dashboard/_layout/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLayoutLeadsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/lembretes': {
      id: '/dashboard/_layout/lembretes'
      path: '/lembretes'
      fullPath: '/dashboard/lembretes'
      preLoaderRoute: typeof DashboardLayoutLembretesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/marca': {
      id: '/dashboard/_layout/marca'
      path: '/marca'
      fullPath: '/dashboard/marca'
      preLoaderRoute: typeof DashboardLayoutMarcaRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/precos': {
      id: '/dashboard/_layout/precos'
      path: '/precos'
      fullPath: '/dashboard/precos'
      preLoaderRoute: typeof DashboardLayoutPrecosRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/produtores': {
      id: '/dashboard/_layout/produtores'
      path: '/produtores'
      fullPath: '/dashboard/produtores'
      preLoaderRoute: typeof DashboardLayoutProdutoresRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/relatorios': {
      id: '/dashboard/_layout/relatorios'
      path: '/relatorios'
      fullPath: '/dashboard/relatorios'
      preLoaderRoute: typeof DashboardLayoutRelatoriosRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutAlertasRoute: typeof DashboardLayoutAlertasRoute
  DashboardLayoutAssinaturaRoute: typeof DashboardLayoutAssinaturaRoute
  DashboardLayoutClimaRoute: typeof DashboardLayoutClimaRoute
  DashboardLayoutEquipeRoute: typeof DashboardLayoutEquipeRoute
  DashboardLayoutFuncionariosRoute: typeof DashboardLayoutFuncionariosRoute
  DashboardLayoutLeadsRoute: typeof DashboardLayoutLeadsRoute
  DashboardLayoutLembretesRoute: typeof DashboardLayoutLembretesRoute
  DashboardLayoutMarcaRoute: typeof DashboardLayoutMarcaRoute
  DashboardLayoutPrecosRoute: typeof DashboardLayoutPrecosRoute
  DashboardLayoutProdutoresRoute: typeof DashboardLayoutProdutoresRoute
  DashboardLayoutRelatoriosRoute: typeof DashboardLayoutRelatoriosRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutAlertasRoute: DashboardLayoutAlertasRoute,
  DashboardLayoutAssinaturaRoute: DashboardLayoutAssinaturaRoute,
  DashboardLayoutClimaRoute: DashboardLayoutClimaRoute,
  DashboardLayoutEquipeRoute: DashboardLayoutEquipeRoute,
  DashboardLayoutFuncionariosRoute: DashboardLayoutFuncionariosRoute,
  DashboardLayoutLeadsRoute: DashboardLayoutLeadsRoute,
  DashboardLayoutLembretesRoute: DashboardLayoutLembretesRoute,
  DashboardLayoutMarcaRoute: DashboardLayoutMarcaRoute,
  DashboardLayoutPrecosRoute: DashboardLayoutPrecosRoute,
  DashboardLayoutProdutoresRoute: DashboardLayoutProdutoresRoute,
  DashboardLayoutRelatoriosRoute: DashboardLayoutRelatoriosRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinarRoute: AssinarRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  ApiAsaasWebhookRoute: ApiAsaasWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
